version: 0.2


phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - java -version
      - mvn clean install -Dmaven.test.skip=true
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/sample-app-1.0.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
